print("Первое число")
first = input()
print("Второе число")
second = input()
print(int(first) + int(second))
print(int(first) - int(second))
print(int(first) * int(second))
print(int(first) / int(second))